[ALPS02186449] Sound: fix kernel build error
[Detail]
build error when CONFIG_MTK_LEGACY is not set
mt_soc_audio_6580/mt_soc_afe_control.c:831:3: error: implicit
declaration of function AudDrv_GPIO_PMIC_Select
[-Werror=implicit-function-declaration]AudDrv_GPIO_PMIC_Select(bEnable);
mt_soc_audio_6580/mt_soc_codec_63xx.c:1710:21: error: pin_extspkamp
defined but not used [-Werror=unused-variable]
static unsigned int pin_extspkamp;
[Solution]
resolve the build error
[Feature] Phone Sound

MTK-Commit-Id: 763caf0735d5a5e7e1c9ef3ef6fb4dc3dca09c83

Change-Id: I0cd906fcec6b9a85f2e8460f167f000585f474bd
CR-Id: ALPS02186449
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>