[ALPS02210363] net: fix build warning in sysctl_net_core.c
[Detail]
Since commit c48cf4f27d455 ("net: sysctl_net_core: check
SNDBUF and RCVBUF for min length") the global variable one
is not used anymore and cause build warning:
net/core/sysctl_net_core.c:26:12: error: one defined but not used [-Werror=unused-variable]

[Solution]
Remove the one to fix it.

[Feature] net

MTK-Commit-Id: aa0cffbba19936ce8c1082e7982b6470a799ba74

Change-Id: Ic44c7ff93c4d4e171d03a7ccdf9c8c3f97504ce4
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02210363