[ALPS02444798] rtc: mt6397: fix build on some 32bits platforms
[Detail]
On some !ARM 32bits platforms, the following compilation error happens
because of the division on a 64bits value in mtk_rtc_read_time():

drivers/built-in.o: In function `mtk_rtc_read_time:
rtc-mt6397.c:(.text+0x265d13f): undefined reference to `__divdi3
rtc-mt6397.c:(.text+0x265d150): undefined reference to `__moddi3

Use div_s64() as done in rtc_time64_to_tm() to solve that.

MTK-Commit-Id: cf4d0a7308962eaa5f0130ecedfd2649af3cbb2e

Change-Id: Iae39ba67de2825e81b8f120a5ad01ca62eebc2f2
CR-Id: ALPS02444798
Feature: RTC
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Acked-by: Eddie Huang <eddie.huang@mediatek.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@free-electrons.com>
(cherry picked from commit 9393996761e23280f259d706133c8f0cd139fd58)