[ALPS02320974] usb : fix build warning on xhci
[Detail]
kernel-3.18/drivers/usb/host/xhci-mtk.h:86:57: error: struct xhci_hcd
declared inside parameter list [-Werror]
kernel-3.18/drivers/usb/host/xhci-mtk.h:86:57: error: its scope is only
this definition or declaration, which is probably not what you want [-Werror]
kernel-3.18/drivers/usb/host/xhci-mtk.h:86:57: error: struct usb_hcd
declared inside parameter list [-Werror]

[Solution]
add include "xhci.h" to xhci-mtk.h

[Feature] [Android Default] USB OTG

MTK-Commit-Id: 3feb18d81f31f55a9f8c5e55c1cf75c3674ff268

Change-Id: I3cffdb9a98d2f5cce44c2f43a1fecd79855d508a
Signed-off-by: Shangbing Hu <shangbing.hu@mediatek.com>
CR-Id: ALPS02320974